TO DECREASE; REDUCE
TO GIVE UP A POSITION, RIGHT, OR POWER
DEVIATING FROM WHAT IS NORMAL
TEMPORARY SUPPRESSION OR SUSPENSION
MISERABLE; PITIFUL
TO REJECT; ABANDON FORMALLY
N. THE ACT OF CUTTING; THE NATURAL SEPARATION OF A LEAF OR OTHER PART OF A PLANT, V. TO CUT OFF OR AWAY (ABSCISE)
TO DEPART SECRETLY
MODERATE IN APPETITE
THE GIVING UP OF CERTAIN PLEASURES
VERY BAD
GROWTH IN SIZE OR INCREASE IN AMOUNT
TO ACCUMULATE; GROW BY ADDITIONS
UNCOMPROMISING; UNYIELDING
SOMETHING ADDED, ATTACHED, OR JOINED
TO CAUTION OR REPRIMAND
TO CORRUPT OR MAKE IMPURE
ADJ. RELATING TO BEAUTY OR ART, N. A CONCEPTION OF WHAT IS ARTISTICALLY BEAUTIFUL
PRETENTIOUS, PHONY
FONDNESS; LIKING; SIMILARITY
TO MAKE LARGER OR GREATER
ADJ. AMOUNTING TO A WHOLE; TOTAL, V. TO COLLECT INTO A MASS, N. COLLECTIVE MASS OR SUM
CHEERFUL WILLINGNESS; EAGERNESS; SPEED
MEDIEVAL CHEMICAL PHILOSOPHY BASED ON CHANGING METAL INTO GOLD; A SEEMINGLY MAGICAL POWER OR PROCESS OF TRANSMUTATION
TO LESSEN; EASE; SOOTHE
TO RELIEVE; IMPROVE PARTIALLY
A COMBINATION; A MIXTURE OF TWO OR MORE METALS